### ISSUE TITLE
Issue with `/join Discord.js` (Discord.js isn't a guild)

### ISSUE THREAD

**Issue by datitisev** [GusCaplan/retrocord#1]
```js
> /join Discord.js
readline.js:982
            throw err;
            ^

TypeError: Cannot read property 'trim' of undefined
    at CommandInstance.<anonymous> (./node_modules/retrocord/src/index.js:100:77)
    at EventEmitter.session.execCommandSet (./node_modules/vorpal/dist/session.js:470:20)
    at EventEmitter.vorpal._exec (./node_modules/vorpal/dist/vorpal.js:960:18)
    at EventEmitter.vorpal._execQueueItem (./node_modules/vorpal/dist/vorpal.js:751:17)
    at EventEmitter.vorpal._queueHandler (./node_modules/vorpal/dist/vorpal.js:735:10)
    at EventEmitter.vorpal.exec (./node_modules/vorpal/dist/vorpal.js:682:10)
    at ./node_modules/vorpal/dist/vorpal.js:625:10
    at .completed (./node_modules/vorpal/dist/ui.js:219:13)
    at PromptUI.onCompletion (./node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (./node_modules/rx-lite/rx.lite.js:1550:12
```

**Comment by GusCaplan** [comment]
fixed in https://github.com/GusCaplan/retrocord/commit/0a571c04a9084377d5d5dc03712a055ed0716af5#diff-19ceca1088a3723f20e09b592ffe7c45R6
